### ISSUE TITLE
Some features

### ISSUE THREAD

**Issue by velvetflower** [ImKitty/Steam-Gametime-Idle#1]
Hi. Thanks for your app. 
Can you add a button that can add more textboxes in multigame idling?

**Comment by ImKitty** [comment]
Hi, i can see what i can do, i think i got an idea for it, i can inform you when its done 👍

**Comment by ImKitty** [comment]
I have updated it with a page system. it now idles maximum of 60 games at once, i tried 90 but those games didnt show in steam itself so maximum 60 is also confirmed, Version 0.7 shall be released in a bit

-Kitty
